version: '3.8'
services:
  web:
    build: . # Isso diz ao Docker para construir a imagem usando o Dockerfile no diretório atual
    ports:
      - "8082:80" # Mapeia a porta 80 do host para a porta 80 do container
    volumes:
      # Opcional: Se você quiser que as mudanças nos seus arquivos HTML no host sejam refletidas automaticamente no container
      # sem precisar reconstruir a imagem, você pode usar um volume.
      # Remova ou comente esta linha se não quiser essa funcionalidade.
      - ./html:/usr/share/nginx/html
    restart: always # Garante que o container reinicie automaticamente se parar
