version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: 'gitlab.example.com' # Substitua
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://129.121.50.125/'; # Substitua
    ports:
      - '8082:80'
      - '82443:443'
      - '8222:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'
    restart: unless-stopped
    networks:
      - gitlab-network

volumes:
  gitlab-config:
    name: gitlab-config
  gitlab-logs:
    name: gitlab-logs
  gitlab-data:
    name: gitlab-data

networks:
  gitlab-network:
    name: gitlab-network
